kind: pipeline
name: build

steps:
  - name: build
    image: turboregistry:5000/juju/turbo-ci-arch
    commands:
      - rustup component add rust-src
      - make

  - name: release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: api_key
      base_url: http://gitea_web_1:3000
      files: julios.iso
    when:
      event: tag
